# Generated by Django 5.0.7 on 2024-07-25 09:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_ingredient_quantity_alter_recipe_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='photo',
            field=models.ImageField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
