# Generated by Django 5.0.7 on 2024-07-25 10:24

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_recipe_photo_alter_recipe_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингридиент', 'verbose_name_plural': 'Ингридиенты'},
        ),
        migrations.AlterModelOptions(
            name='kitchen',
            options={'verbose_name': 'Кухня', 'verbose_name_plural': 'Кухни'},
        ),
        migrations.AlterModelOptions(
            name='recipe',
            options={'verbose_name': 'Рецепт', 'verbose_name_plural': 'Рецепты'},
        ),
        migrations.AddField(
            model_name='recipe',
            name='yields',
            field=models.PositiveIntegerField(blank=True, help_text='Порция', null=True, verbose_name='Порция'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.PositiveIntegerField(help_text='Время готовки в минутах', verbose_name='Время готовки в минутах'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main.ingredient', verbose_name='Ингридиенты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=ckeditor.fields.RichTextField(verbose_name='Инструкция'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='kitchen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='main.kitchen', verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
    ]
