# Generated by Django 5.0.7 on 2024-07-26 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_alter_recipe_cook_time_alter_recipe_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Фото'),
        ),
    ]
