# Generated by Django 5.0.7 on 2024-07-27 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_ingredient_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='kitchen',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='category/', verbose_name='Фото'),
        ),
    ]
