# Generated by Django 5.0.7 on 2024-07-28 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_kitchen_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(blank=True, upload_to='category/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='kitchen',
            name='photo',
            field=models.ImageField(blank=True, upload_to='category/', verbose_name='Фото'),
        ),
    ]
